/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: high_score.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "high_score.pb-c.h"
void   high_score__init
                     (HighScore         *message)
{
  static const HighScore init_value = HIGH_SCORE__INIT;
  *message = init_value;
}
size_t high_score__get_packed_size
                     (const HighScore *message)
{
  assert(message->base.descriptor == &high_score__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t high_score__pack
                     (const HighScore *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &high_score__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t high_score__pack_to_buffer
                     (const HighScore *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &high_score__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HighScore *
       high_score__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HighScore *)
     protobuf_c_message_unpack (&high_score__descriptor,
                                allocator, len, data);
}
void   high_score__free_unpacked
                     (HighScore *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &high_score__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor high_score__field_descriptors[1] =
{
  {
    "num",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(HighScore, has_num),
    offsetof(HighScore, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned high_score__field_indices_by_name[] = {
  0,   /* field[0] = num */
};
static const ProtobufCIntRange high_score__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor high_score__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HighScore",
  "HighScore",
  "HighScore",
  "",
  sizeof(HighScore),
  1,
  high_score__field_descriptors,
  high_score__field_indices_by_name,
  1,  high_score__number_ranges,
  (ProtobufCMessageInit) high_score__init,
  NULL,NULL,NULL    /* reserved[123] */
};
